version: 0.8
index_id: logs-opensase-sdk
index_uri: s3://quickwit-index/logs-opensase-sdk
doc_mapping:
  field_mappings:
    - name: timestamp
      type: datetime
      fast: true
    - name: level
      type: text
      tokenizer: raw
    - name: service
      type: text
      tokenizer: raw
    - name: trace_id
      type: text
      tokenizer: raw
    - name: span_id
      type: text
      tokenizer: raw
    - name: tenant_id
      type: text
      tokenizer: raw
    - name: message
      type: text
    - name: attrs
      type: json
  timestamp_field: timestamp
indexing_settings:
  commit_timeout_secs: 2
search_settings:
  default_search_fields: [message, service, trace_id]
